export const MESSAGE_MODAL_OPEN = 'MESSAGE_MODAL_OPEN';
export const MESSAGE_MODAL_CLOSE = 'MESSAGE_MODAL_CLOSE';
export const CONFIRM_MODAL_OPEN = 'CONFIRM_MODAL_OPEN';
export const CONFIRM_MODAL_CLOSE = 'CONFIRM_MODAL_CLOSE';
